### ISSUE TITLE
Ahoj, skúšal som to či to funguje ale nič sa nestalo po pridaní kódu.

### ISSUE THREAD

**Issue by KexoTV** [milemaciciky/edupagetesthack#30]

**Comment by ivanhrabcak** [comment]
Ahoj, ak si pouzil rozsirenie spravne (po instalacii refreshol stranku, klikol na ikonku po spusteni testu), tak aj ked rozsirenie na konkretny test nefunguje, mal by si vidiet nad kazdou otazkou chybu. Ak si postupoval spravne, vidis v konzoli chyby? Ak nie, prosim zatvor tuto issue.

**Comment by KexoTV** [comment]
Vyskúšam to znova keď budem mať prístup na test, cize toto uzatvorím a keď mi to znova nebude fungovať tak otvorím nový issue s sceeenshotom.
